Repository nanafox/sorting_algorithms, pull requests merged in 2024-01, with the labels that each got.

#1 Added solution for the Selection Sort Algorithm task
  .gitignore
  2-0
  2-selection_sort.c
  sort.h
Labels: enhancement

#2 Removed the 'stdbool' header file and updated code
  2-selection_sort.c
  sort.h
Labels: bug

#3 Implemented a bubble sort algorithm
  0-O
  0-bubble_sort.c
Labels: enhancement

#5 Implemented the Insertion Sort Algorithm
  1-O
  1-insertion_sort_list.c
Labels: enhancement

#9 Optimized the quick sort algorithm
  3-O
  3-main.c
  3-quick_sort.c
  sort.h
Labels: bug, enhancement

#12 Implemented the Quick Sort Algorithm using the Hoare Partition Scheme
  107-O
  107-quick_sort_hoare.c
  3-quick_sort.c
  sort.h
Labels: enhancement
